# Generated by Django 4.2.7 on 2024-03-14 14:07

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_mofified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
