# Generated by Django 4.2.7 on 2024-03-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='branch_code',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
