# Generated by Django 4.2.7 on 2024-03-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_employee_branch_remove_employee_branch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch_code',
            field=models.CharField(default=3, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_code', models.CharField(max_length=6, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
            preserve_default=False,
        ),
    ]
