# Generated by Django 4.2.7 on 2024-03-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee_branch_code_branch_employee_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_mofified',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
