# Generated by Django 4.2.7 on 2024-03-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
