# Generated by Django 4.2.7 on 2024-03-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_employee_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
