# Generated by Django 4.2.7 on 2024-03-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_companypost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypost',
            name='image',
        ),
    ]
