# Generated by Django 4.2.7 on 2024-03-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_companypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_post'),
        ),
    ]
