# Generated by Django 4.2.7 on 2024-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypost',
            name='description',
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee'),
        ),
    ]
