# Generated by Django 4.2.7 on 2024-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_companypost_description_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypost',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
